### ISSUE TITLE
Addon no longer working

### ISSUE THREAD

**Issue by theres-waldo** [mikeconley/rb-doubleclick#1]
This seems to have stopped working. Perhaps something on the reviewboard/MozReview end has changed?

**Comment by mikeconley** [comment]
Hey, thanks. I think I fixed this in 0.0.2 - [give it a shot and let me know](https://addons.mozilla.org/en-US/firefox/addon/rb-doubleclick/versions/)?

**Comment by theres-waldo** [comment]
Working now - thanks a lot!

**Comment by mikeconley** [comment]
Np! Thanks for reporting!
